SONGS = [
    ("Tití Me Preguntó", "Bad Bunny", "Un Verano Sin Ti"),
    ("Me Porto Bonito", "Bad Bunny", "Un Verano Sin Ti"),
    ("Ojitos Lindos", "Bad Bunny", "Un Verano Sin Ti"),
    ("Moscow Mule", "Bad Bunny", "Un Verano Sin Ti"),
    ("Efecto", "Bad Bunny", "Un Verano Sin Ti"),
    ("Neverita", "Bad Bunny", "Un Verano Sin Ti"),
    ("Callaíta", "Bad Bunny", "YHLQMDLG"),
    ("Safaera", "Bad Bunny", "YHLQMDLG"),
    ("Yo Perreo Sola", "Bad Bunny", "YHLQMDLG"),
    ("La Canción", "Bad Bunny", "Oasis"),
    ("Amorfoda", "Bad Bunny", "X 100PRE"),
    ("Ni Bien Ni Mal", "Bad Bunny", "X 100PRE"),
    ("DÁKITI", "Bad Bunny", "El Último Tour del Mundo"),
    ("La Noche de Anoche", "Bad Bunny", "El Último Tour del Mundo"),
    ("Yonaguni", "Bad Bunny", "Single"),
    ("Un Preview", "Bad Bunny", "Single"),
    ("Where She Goes", "Bad Bunny", "Single"),
    ("Un Ratito", "Bad Bunny", "Un Verano Sin Ti"),
    ("Party", "Bad Bunny", "Un Verano Sin Ti"),
    ("Tarot", "Bad Bunny", "Un Verano Sin Ti"),
    ("High", "Rawayana", "Trippy Caribbean"),
    ("Sin Ti", "Rawayana", "Trippy Caribbean"),
    ("Feriado", "Rawayana", "Licencia Para Ser Libre"),
    ("Binikini", "Rawayana", "Licencia Para Ser Libre"),
    ("Algo Distinto", "Rawayana", "Licencia Para Ser Libre"),
    ("Véngase", "Rawayana", "Rawayanaland"),
    ("Into You", "Rawayana", "Rawayanaland"),
    ("Camarones y Vinito", "Rawayana", "Rawayanaland"),
    ("Welcome to el Sur", "Rawayana", "Rawayanaland"),
    ("Dame un Break", "Rawayana", "Licencia Para Ser Libre"),
    ("drivers license", "Olivia Rodrigo", "SOUR"),
    ("good 4 u", "Olivia Rodrigo", "SOUR"),
    ("deja vu", "Olivia Rodrigo", "SOUR"),
    ("traitor", "Olivia Rodrigo", "SOUR"),
    ("happier", "Olivia Rodrigo", "SOUR"),
    ("brutal", "Olivia Rodrigo", "SOUR"),
    ("1 step forward, 3 steps back", "Olivia Rodrigo", "SOUR"),
    ("vampire", "Olivia Rodrigo", "GUTS"),
    ("bad idea right?", "Olivia Rodrigo", "GUTS"),
    ("get him back!", "Olivia Rodrigo", "GUTS"),
    ("all-american bitch", "Olivia Rodrigo", "GUTS"),
    ("ballad of a homeschooled girl", "Olivia Rodrigo", "GUTS"),
    ("logical", "Olivia Rodrigo", "GUTS"),
    ("Espresso", "Sabrina Carpenter", "Short n' Sweet"),
    ("Please Please Please", "Sabrina Carpenter", "Short n' Sweet"),
    ("Feather", "Sabrina Carpenter", "emails i can't send"),
    ("Nonsense", "Sabrina Carpenter", "emails i can't send"),
    ("because i liked a boy", "Sabrina Carpenter", "emails i can't send"),
    ("Skinny Dipping", "Sabrina Carpenter", "emails i can't send"),
    ("Fast Times", "Sabrina Carpenter", "emails i can't send"),
    ("Thumbs", "Sabrina Carpenter", "EVOLution"),
    ("Sue Me", "Sabrina Carpenter", "Singular: Act I"),
    ("Almost Love", "Sabrina Carpenter", "Singular: Act I"),
    ("Hawái", "Maluma", "Papi Juancho"),
    ("Sobrio", "Maluma", "The Love & Sex Tape"),
    ("Felices los 4", "Maluma", "F.A.M.E."),
    ("Borró Cassette", "Maluma", "Pretty Boy, Dirty Boy"),
    ("Corazón", "Maluma", "F.A.M.E."),
    ("Junio", "Maluma", "The Love & Sex Tape"),
    ("Según Quién", "Maluma", "Don Juan"),
    ("ADMV", "Maluma", "Single"),
    ("Amigos Con Derechos", "Maluma", "F.A.M.E."),
    ("4 Babys", "Maluma", "Pretty Boy, Dirty Boy"),
    ("TQG", "Karol G", "Mañana Será Bonito"),
    ("Provenza", "Karol G", "Mañana Será Bonito"),
    ("Bichota", "Karol G", "KG0516"),
    ("El Makinon", "Karol G", "KG0516"),
    ("200 Copas", "Karol G", "KG0516"),
    ("MAMIII", "Karol G", "Single"),
    ("Mientras Me Curo del Cora", "Karol G", "Mañana Será Bonito"),
    ("Cairo", "Karol G", "Mañana Será Bonito"),
    ("Gucci Los Paños", "Karol G", "KG0516"),
    ("Ocean", "Karol G", "Ocean"),
    ("Blinding Lights", "The Weeknd", "After Hours"),
    ("Save Your Tears", "The Weeknd", "After Hours"),
    ("Starboy", "The Weeknd", "Starboy"),
    ("The Hills", "The Weeknd", "Beauty Behind the Madness"),
    ("Can't Feel My Face", "The Weeknd", "Beauty Behind the Madness"),
    ("Die For You", "The Weeknd", "Starboy"),
    ("Earned It", "The Weeknd", "Fifty Shades of Grey"),
    ("Take My Breath", "The Weeknd", "Dawn FM"),
    ("Sacrifice", "The Weeknd", "Dawn FM"),
    ("Less Than Zero", "The Weeknd", "Dawn FM"),
    ("7 rings", "Ariana Grande", "thank u, next"),
    ("thank u, next", "Ariana Grande", "thank u, next"),
    ("Positions", "Ariana Grande", "Positions"),
    ("Into You", "Ariana Grande", "Dangerous Woman"),
    ("No Tears Left to Cry", "Ariana Grande", "Sweetener"),
    ("One Last Time", "Ariana Grande", "My Everything"),
    ("Break Free", "Ariana Grande", "My Everything"),
    ("problem", "Ariana Grande", "My Everything"),
    ("God is a woman", "Ariana Grande", "Sweetener"),
    ("We Can't Be Friends (Wait for Your Love)", "Ariana Grande", "Eternal Sunshine"),
    ("Mi Gente", "J Balvin", "Vibras"),
    ("Ginza", "J Balvin", "Energía"),
    ("Ay Vamos", "J Balvin", "La Familia"),
    ("Safari", "J Balvin", "Energía"),
    ("Reggaeton", "J Balvin", "Vibras"),
    ("Blanco", "J Balvin", "Colores"),
    ("6 AM", "J Balvin", "La Familia"),
]